name: Build App Image (Manual)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Local image tag to build'
        required: false
        default: 'manage-system:test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show result
        run: |
          echo "Built image tag: ${{ inputs.image_tag }}"
